// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module axil_conv2D_axil_conv2D_Pipeline_loop_i_loop_j (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        image_in_address0,
        image_in_ce0,
        image_in_q0,
        conv3_i_i97,
        conv3_i_i97_15,
        conv3_i_i97_214,
        conv3_i_i97_1,
        conv3_i_i97_1_1,
        conv3_i_i97_1_2,
        conv3_i_i97_2,
        conv3_i_i97_2_1,
        conv3_i_i97_2_2,
        empty,
        image_out_address0,
        image_out_ce0,
        image_out_we0,
        image_out_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 9'd1;
parameter    ap_ST_fsm_pp0_stage1 = 9'd2;
parameter    ap_ST_fsm_pp0_stage2 = 9'd4;
parameter    ap_ST_fsm_pp0_stage3 = 9'd8;
parameter    ap_ST_fsm_pp0_stage4 = 9'd16;
parameter    ap_ST_fsm_pp0_stage5 = 9'd32;
parameter    ap_ST_fsm_pp0_stage6 = 9'd64;
parameter    ap_ST_fsm_pp0_stage7 = 9'd128;
parameter    ap_ST_fsm_pp0_stage8 = 9'd256;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [12:0] image_in_address0;
output   image_in_ce0;
input  [7:0] image_in_q0;
input  [7:0] conv3_i_i97;
input  [7:0] conv3_i_i97_15;
input  [7:0] conv3_i_i97_214;
input  [7:0] conv3_i_i97_1;
input  [7:0] conv3_i_i97_1_1;
input  [7:0] conv3_i_i97_1_2;
input  [7:0] conv3_i_i97_2;
input  [7:0] conv3_i_i97_2_1;
input  [7:0] conv3_i_i97_2_2;
input  [20:0] empty;
output  [12:0] image_out_address0;
output   image_out_ce0;
output   image_out_we0;
output  [7:0] image_out_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage8;
wire    ap_block_pp0_stage8_subdone;
wire   [0:0] icmp_ln25_fu_681_p2;
reg    ap_condition_exit_pp0_iter0_stage8;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [0:0] icmp_ln278_reg_288;
reg   [7:0] reg_299;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_11001;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_pp0_stage5_11001;
wire    ap_CS_fsm_pp0_stage6;
wire    ap_block_pp0_stage6_11001;
wire    ap_CS_fsm_pp0_stage7;
wire    ap_block_pp0_stage7_11001;
wire    ap_block_pp0_stage0_11001;
wire  signed [15:0] conv3_i_i97_2_2_cast_fu_303_p1;
reg  signed [15:0] conv3_i_i97_2_2_cast_reg_897;
wire  signed [15:0] conv3_i_i97_2_1_cast_fu_307_p1;
reg  signed [15:0] conv3_i_i97_2_1_cast_reg_902;
wire  signed [15:0] conv3_i_i97_2_cast_fu_311_p1;
reg  signed [15:0] conv3_i_i97_2_cast_reg_907;
wire  signed [15:0] conv3_i_i97_1_2_cast_fu_315_p1;
reg  signed [15:0] conv3_i_i97_1_2_cast_reg_912;
wire  signed [15:0] conv3_i_i97_1_1_cast_fu_319_p1;
reg  signed [15:0] conv3_i_i97_1_1_cast_reg_917;
wire  signed [15:0] conv3_i_i97_1_cast_fu_323_p1;
reg  signed [15:0] conv3_i_i97_1_cast_reg_922;
wire  signed [15:0] conv3_i_i97_214_cast_fu_327_p1;
reg  signed [15:0] conv3_i_i97_214_cast_reg_927;
wire  signed [15:0] conv3_i_i97_15_cast_fu_331_p1;
reg  signed [15:0] conv3_i_i97_15_cast_reg_932;
wire  signed [15:0] conv3_i_i97_cast_fu_335_p1;
reg  signed [15:0] conv3_i_i97_cast_reg_937;
wire   [12:0] select_ln25_fu_393_p3;
reg   [12:0] select_ln25_reg_942;
wire   [12:0] select_ln25_3_fu_401_p3;
reg   [12:0] select_ln25_3_reg_954;
wire   [12:0] image_1d_idx_7_fu_463_p2;
reg   [12:0] image_1d_idx_7_reg_974;
reg   [7:0] image_in_load_1_reg_989;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3_11001;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_pp0_stage4_11001;
wire   [12:0] grp_fu_778_p3;
reg   [12:0] add_ln52_reg_1019;
wire  signed [16:0] grp_fu_786_p3;
reg  signed [16:0] add_ln40_5_reg_1034;
wire  signed [17:0] grp_fu_793_p3;
reg  signed [17:0] add_ln40_6_reg_1064;
wire    ap_block_pp0_stage8_11001;
wire   [18:0] add_ln40_7_fu_658_p2;
reg   [18:0] add_ln40_7_reg_1084;
wire   [0:0] icmp_ln27_fu_670_p2;
reg   [0:0] icmp_ln27_reg_1089;
reg   [0:0] icmp_ln25_reg_1094;
wire  signed [16:0] grp_fu_808_p3;
reg  signed [16:0] add_ln40_1_reg_1103;
wire  signed [20:0] grp_fu_815_p3;
reg  signed [20:0] add_ln40_reg_1108;
wire   [20:0] acc_fu_720_p2;
reg   [20:0] acc_reg_1118;
reg   [12:0] tmp_1_reg_1124;
wire   [7:0] acc_sat_1_fu_765_p3;
reg    ap_enable_reg_pp0_iter0_reg;
wire    ap_block_pp0_stage5_subdone;
reg   [0:0] ap_phi_mux_icmp_ln278_phi_fu_291_p4;
wire    ap_loop_init;
wire    ap_block_pp0_stage0_subdone;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln37_7_fu_415_p1;
wire   [63:0] zext_ln27_1_fu_443_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln37_fu_468_p1;
wire    ap_block_pp0_stage2;
wire   [63:0] zext_ln37_1_fu_498_p1;
wire    ap_block_pp0_stage3;
wire   [63:0] zext_ln37_3_fu_549_p1;
wire    ap_block_pp0_stage4;
wire   [63:0] zext_ln37_2_fu_563_p1;
wire    ap_block_pp0_stage5;
wire   [63:0] zext_ln37_4_fu_577_p1;
wire    ap_block_pp0_stage6;
wire   [63:0] zext_ln37_5_fu_603_p1;
wire    ap_block_pp0_stage7;
wire   [63:0] zext_ln37_6_fu_647_p1;
wire    ap_block_pp0_stage8;
wire   [63:0] zext_ln52_1_fu_774_p1;
reg   [12:0] indvar_flatten2_fu_102;
wire   [12:0] add_ln25_2_fu_664_p2;
reg   [12:0] indvars_iv353_fu_106;
wire   [12:0] select_ln25_2_fu_617_p3;
reg   [12:0] indvars_iv4_fu_110;
reg   [12:0] ap_sig_allocacmp_indvars_iv4_load;
reg   [6:0] i5_fu_114;
wire   [6:0] i_2_fu_431_p3;
reg   [12:0] image_1d_idx6_fu_118;
reg   [12:0] ap_sig_allocacmp_image_1d_idx6_load;
reg   [6:0] j7_fu_122;
wire   [6:0] j_fu_507_p2;
reg   [6:0] i_19_fu_126;
wire   [6:0] i_fu_447_p2;
reg   [12:0] add_ln2510_fu_130;
wire   [12:0] add_ln25_fu_513_p2;
reg   [12:0] ap_sig_allocacmp_add_ln2510_load;
reg   [12:0] add_ln25_111_fu_134;
wire   [12:0] add_ln25_1_fu_675_p2;
reg    image_in_ce0_local;
reg   [12:0] image_in_address0_local;
reg    image_out_we0_local;
reg    image_out_ce0_local;
wire   [12:0] image_1d_idx_6_fu_409_p2;
wire   [12:0] image_1d_idx_fu_493_p2;
wire   [6:0] select_ln25_1_fu_485_p3;
wire   [7:0] mul_ln40_1_fu_531_p0;
wire  signed [7:0] mul_ln40_1_fu_531_p1;
wire  signed [15:0] mul_ln40_1_fu_531_p2;
wire   [12:0] image_1d_idx_2_fu_544_p2;
wire   [12:0] image_1d_idx_1_fu_558_p2;
wire   [12:0] image_1d_idx_3_fu_572_p2;
wire   [7:0] mul_ln40_3_fu_589_p0;
wire  signed [7:0] mul_ln40_3_fu_589_p1;
wire  signed [15:0] mul_ln40_3_fu_589_p2;
wire   [12:0] image_1d_idx_4_fu_598_p2;
wire   [7:0] mul_ln40_5_fu_629_p0;
wire  signed [7:0] mul_ln40_5_fu_629_p1;
wire  signed [15:0] mul_ln40_5_fu_629_p2;
wire   [12:0] image_1d_idx_5_fu_642_p2;
wire  signed [16:0] grp_fu_800_p3;
wire  signed [18:0] sext_ln40_6_fu_655_p1;
wire  signed [18:0] sext_ln40_4_fu_652_p1;
wire  signed [17:0] grp_fu_821_p3;
wire  signed [20:0] sext_ln40_3_fu_709_p1;
wire  signed [20:0] sext_ln40_7_fu_717_p1;
(* use_dsp48 = "no" *) wire   [20:0] add_ln40_3_fu_712_p2;
wire   [0:0] icmp_ln45_fu_736_p2;
wire   [0:0] tmp_2_fu_741_p3;
wire   [0:0] empty_14_fu_759_p2;
wire   [7:0] acc_sat_fu_751_p3;
wire   [7:0] trunc_ln50_fu_748_p1;
wire   [6:0] grp_fu_778_p0;
wire   [6:0] grp_fu_778_p1;
wire   [6:0] grp_fu_778_p2;
wire   [7:0] grp_fu_786_p0;
wire  signed [7:0] grp_fu_786_p1;
wire   [7:0] grp_fu_793_p0;
wire  signed [7:0] grp_fu_793_p1;
wire   [7:0] grp_fu_800_p0;
wire  signed [7:0] grp_fu_800_p1;
wire   [7:0] grp_fu_808_p0;
wire  signed [7:0] grp_fu_808_p1;
wire   [7:0] grp_fu_815_p0;
wire  signed [7:0] grp_fu_815_p1;
wire   [7:0] grp_fu_821_p0;
wire  signed [7:0] grp_fu_821_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter1_stage5;
reg    ap_idle_pp0_0to0;
reg   [8:0] ap_NS_fsm;
reg    ap_idle_pp0_1to1;
wire    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage2_subdone;
wire    ap_block_pp0_stage3_subdone;
wire    ap_block_pp0_stage4_subdone;
wire    ap_block_pp0_stage6_subdone;
wire    ap_block_pp0_stage7_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [12:0] grp_fu_778_p00;
wire   [12:0] grp_fu_778_p20;
wire   [15:0] grp_fu_786_p00;
wire   [15:0] grp_fu_793_p00;
wire   [15:0] grp_fu_800_p00;
wire   [15:0] grp_fu_808_p00;
wire   [15:0] grp_fu_815_p00;
wire   [15:0] grp_fu_821_p00;
wire   [15:0] mul_ln40_1_fu_531_p00;
wire   [15:0] mul_ln40_3_fu_589_p00;
wire   [15:0] mul_ln40_5_fu_629_p00;
reg    ap_condition_800;
reg    ap_condition_805;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 9'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 indvar_flatten2_fu_102 = 13'd0;
#0 indvars_iv353_fu_106 = 13'd0;
#0 indvars_iv4_fu_110 = 13'd0;
#0 i5_fu_114 = 7'd0;
#0 image_1d_idx6_fu_118 = 13'd0;
#0 j7_fu_122 = 7'd0;
#0 i_19_fu_126 = 7'd0;
#0 add_ln2510_fu_130 = 13'd0;
#0 add_ln25_111_fu_134 = 13'd0;
#0 ap_done_reg = 1'b0;
end

axil_conv2D_mul_8ns_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8ns_8s_16_1_1_U1(
    .din0(mul_ln40_1_fu_531_p0),
    .din1(mul_ln40_1_fu_531_p1),
    .dout(mul_ln40_1_fu_531_p2)
);

axil_conv2D_mul_8ns_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8ns_8s_16_1_1_U2(
    .din0(mul_ln40_3_fu_589_p0),
    .din1(mul_ln40_3_fu_589_p1),
    .dout(mul_ln40_3_fu_589_p2)
);

axil_conv2D_mul_8ns_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8ns_8s_16_1_1_U3(
    .din0(mul_ln40_5_fu_629_p0),
    .din1(mul_ln40_5_fu_629_p1),
    .dout(mul_ln40_5_fu_629_p2)
);

axil_conv2D_mac_muladd_7ns_7ns_7ns_13_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 7 ),
    .dout_WIDTH( 13 ))
mac_muladd_7ns_7ns_7ns_13_4_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_778_p0),
    .din1(grp_fu_778_p1),
    .din2(grp_fu_778_p2),
    .ce(1'b1),
    .dout(grp_fu_778_p3)
);

axil_conv2D_mac_muladd_8ns_8s_16s_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8ns_8s_16s_17_4_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_786_p0),
    .din1(grp_fu_786_p1),
    .din2(mul_ln40_1_fu_531_p2),
    .ce(1'b1),
    .dout(grp_fu_786_p3)
);

axil_conv2D_mac_muladd_8ns_8s_17s_18_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 18 ))
mac_muladd_8ns_8s_17s_18_4_1_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_793_p0),
    .din1(grp_fu_793_p1),
    .din2(add_ln40_5_reg_1034),
    .ce(1'b1),
    .dout(grp_fu_793_p3)
);

axil_conv2D_mac_muladd_8ns_8s_16s_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8ns_8s_16s_17_4_1_U7(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_800_p0),
    .din1(grp_fu_800_p1),
    .din2(mul_ln40_3_fu_589_p2),
    .ce(1'b1),
    .dout(grp_fu_800_p3)
);

axil_conv2D_mac_muladd_8ns_8s_16s_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8ns_8s_16s_17_4_1_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_808_p0),
    .din1(grp_fu_808_p1),
    .din2(mul_ln40_5_fu_629_p2),
    .ce(1'b1),
    .dout(grp_fu_808_p3)
);

axil_conv2D_mac_muladd_8ns_8s_21s_21_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 21 ),
    .dout_WIDTH( 21 ))
mac_muladd_8ns_8s_21s_21_4_1_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_815_p0),
    .din1(grp_fu_815_p1),
    .din2(empty),
    .ce(1'b1),
    .dout(grp_fu_815_p3)
);

axil_conv2D_mac_muladd_8ns_8s_17s_18_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 18 ))
mac_muladd_8ns_8s_17s_18_4_1_U10(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_821_p0),
    .din1(grp_fu_821_p1),
    .din2(add_ln40_1_reg_1103),
    .ce(1'b1),
    .dout(grp_fu_821_p3)
);

axil_conv2D_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage8),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage5_subdone) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage5_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage8_subdone) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln2510_fu_130 <= 13'd88;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        add_ln2510_fu_130 <= add_ln25_fu_513_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln25_111_fu_134 <= 13'd174;
    end else if (((1'b0 == ap_block_pp0_stage8_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        add_ln25_111_fu_134 <= add_ln25_1_fu_675_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_loop_exit_ready == 1'b0) & (1'b0 == ap_block_pp0_stage5_subdone) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((ap_idle_pp0_0to0 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter1_stage5)))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage8_11001) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i5_fu_114 <= 7'd0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        i5_fu_114 <= i_2_fu_431_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_19_fu_126 <= 7'd1;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        i_19_fu_126 <= i_fu_447_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_805)) begin
            icmp_ln278_reg_288 <= icmp_ln27_reg_1089;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_init == 1'b1))) begin
            icmp_ln278_reg_288 <= 1'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        image_1d_idx6_fu_118 <= 13'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        image_1d_idx6_fu_118 <= image_1d_idx_7_fu_463_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten2_fu_102 <= 13'd0;
    end else if (((1'b0 == ap_block_pp0_stage8_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        indvar_flatten2_fu_102 <= add_ln25_2_fu_664_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvars_iv353_fu_106 <= 13'd86;
    end else if (((1'b0 == ap_block_pp0_stage8_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        indvars_iv353_fu_106 <= select_ln25_2_fu_617_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
            indvars_iv4_fu_110 <= select_ln25_3_fu_401_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            indvars_iv4_fu_110 <= 13'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        j7_fu_122 <= 7'd0;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        j7_fu_122 <= j_fu_507_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        acc_reg_1118 <= acc_fu_720_p2;
        tmp_1_reg_1124 <= {{acc_fu_720_p2[20:8]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln40_1_reg_1103 <= grp_fu_808_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        add_ln40_5_reg_1034 <= grp_fu_786_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        add_ln40_6_reg_1064 <= grp_fu_793_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage8_11001) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        add_ln40_7_reg_1084 <= add_ln40_7_fu_658_p2;
        icmp_ln25_reg_1094 <= icmp_ln25_fu_681_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        add_ln40_reg_1108 <= grp_fu_815_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        add_ln52_reg_1019 <= grp_fu_778_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv3_i_i97_15_cast_reg_932 <= conv3_i_i97_15_cast_fu_331_p1;
        conv3_i_i97_1_1_cast_reg_917 <= conv3_i_i97_1_1_cast_fu_319_p1;
        conv3_i_i97_1_2_cast_reg_912 <= conv3_i_i97_1_2_cast_fu_315_p1;
        conv3_i_i97_1_cast_reg_922 <= conv3_i_i97_1_cast_fu_323_p1;
        conv3_i_i97_214_cast_reg_927 <= conv3_i_i97_214_cast_fu_327_p1;
        conv3_i_i97_2_1_cast_reg_902 <= conv3_i_i97_2_1_cast_fu_307_p1;
        conv3_i_i97_2_2_cast_reg_897 <= conv3_i_i97_2_2_cast_fu_303_p1;
        conv3_i_i97_2_cast_reg_907 <= conv3_i_i97_2_cast_fu_311_p1;
        conv3_i_i97_cast_reg_937 <= conv3_i_i97_cast_fu_335_p1;
        select_ln25_3_reg_954 <= select_ln25_3_fu_401_p3;
        select_ln25_reg_942 <= select_ln25_fu_393_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage8_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        icmp_ln27_reg_1089 <= icmp_ln27_fu_670_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        image_1d_idx_7_reg_974 <= image_1d_idx_7_fu_463_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        image_in_load_1_reg_989 <= image_in_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)))) begin
        reg_299 <= image_in_q0;
    end
end

always @ (*) begin
    if (((icmp_ln25_fu_681_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage8_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        ap_condition_exit_pp0_iter0_stage8 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage8 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage5_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln25_reg_1094 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        ap_condition_exit_pp0_iter1_stage5 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage5 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage5_subdone) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_800)) begin
            ap_phi_mux_icmp_ln278_phi_fu_291_p4 = icmp_ln27_reg_1089;
        end else if ((ap_loop_init == 1'b1)) begin
            ap_phi_mux_icmp_ln278_phi_fu_291_p4 = 1'd0;
        end else begin
            ap_phi_mux_icmp_ln278_phi_fu_291_p4 = icmp_ln27_reg_1089;
        end
    end else begin
        ap_phi_mux_icmp_ln278_phi_fu_291_p4 = icmp_ln27_reg_1089;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage8_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_add_ln2510_load = 13'd88;
    end else begin
        ap_sig_allocacmp_add_ln2510_load = add_ln2510_fu_130;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_image_1d_idx6_load = 13'd0;
    end else begin
        ap_sig_allocacmp_image_1d_idx6_load = image_1d_idx6_fu_118;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvars_iv4_load = 13'd0;
    end else begin
        ap_sig_allocacmp_indvars_iv4_load = indvars_iv4_fu_110;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage8) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
            image_in_address0_local = zext_ln37_6_fu_647_p1;
        end else if (((1'b0 == ap_block_pp0_stage7) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            image_in_address0_local = zext_ln37_5_fu_603_p1;
        end else if (((1'b0 == ap_block_pp0_stage6) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
            image_in_address0_local = zext_ln37_4_fu_577_p1;
        end else if (((1'b0 == ap_block_pp0_stage5) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            image_in_address0_local = zext_ln37_2_fu_563_p1;
        end else if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            image_in_address0_local = zext_ln37_3_fu_549_p1;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            image_in_address0_local = zext_ln37_1_fu_498_p1;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            image_in_address0_local = zext_ln37_fu_468_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            image_in_address0_local = zext_ln27_1_fu_443_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            image_in_address0_local = zext_ln37_7_fu_415_p1;
        end else begin
            image_in_address0_local = 'bx;
        end
    end else begin
        image_in_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage8_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)))) begin
        image_in_ce0_local = 1'b1;
    end else begin
        image_in_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)))) begin
        image_out_ce0_local = 1'b1;
    end else begin
        image_out_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        image_out_we0_local = 1'b1;
    end else begin
        image_out_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if (((ap_idle_pp0_0to0 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter1_stage5))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_pp0_stage6 : begin
            if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end
        end
        ap_ST_fsm_pp0_stage7 : begin
            if ((1'b0 == ap_block_pp0_stage7_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end
        end
        ap_ST_fsm_pp0_stage8 : begin
            if ((1'b0 == ap_block_pp0_stage8_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage8;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_fu_720_p2 = ($signed(sext_ln40_7_fu_717_p1) + $signed(add_ln40_3_fu_712_p2));

assign acc_sat_1_fu_765_p3 = ((empty_14_fu_759_p2[0:0] == 1'b1) ? acc_sat_fu_751_p3 : trunc_ln50_fu_748_p1);

assign acc_sat_fu_751_p3 = ((icmp_ln45_fu_736_p2[0:0] == 1'b1) ? 8'd255 : 8'd0);

assign add_ln25_1_fu_675_p2 = (select_ln25_2_fu_617_p3 + 13'd88);

assign add_ln25_2_fu_664_p2 = (indvar_flatten2_fu_102 + 13'd1);

assign add_ln25_fu_513_p2 = (select_ln25_3_reg_954 + 13'd88);

assign add_ln40_3_fu_712_p2 = ($signed(sext_ln40_3_fu_709_p1) + $signed(add_ln40_reg_1108));

assign add_ln40_7_fu_658_p2 = ($signed(sext_ln40_6_fu_655_p1) + $signed(sext_ln40_4_fu_652_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp0_stage6 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp0_stage7 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_pp0_stage8 = ap_CS_fsm[32'd8];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_800 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln25_reg_1094 == 1'd0));
end

always @ (*) begin
    ap_condition_805 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln25_reg_1094 == 1'd0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage8;

assign ap_ready = ap_ready_sig;

assign conv3_i_i97_15_cast_fu_331_p1 = $signed(conv3_i_i97_15);

assign conv3_i_i97_1_1_cast_fu_319_p1 = $signed(conv3_i_i97_1_1);

assign conv3_i_i97_1_2_cast_fu_315_p1 = $signed(conv3_i_i97_1_2);

assign conv3_i_i97_1_cast_fu_323_p1 = $signed(conv3_i_i97_1);

assign conv3_i_i97_214_cast_fu_327_p1 = $signed(conv3_i_i97_214);

assign conv3_i_i97_2_1_cast_fu_307_p1 = $signed(conv3_i_i97_2_1);

assign conv3_i_i97_2_2_cast_fu_303_p1 = $signed(conv3_i_i97_2_2);

assign conv3_i_i97_2_cast_fu_311_p1 = $signed(conv3_i_i97_2);

assign conv3_i_i97_cast_fu_335_p1 = $signed(conv3_i_i97);

assign empty_14_fu_759_p2 = (tmp_2_fu_741_p3 | icmp_ln45_fu_736_p2);

assign grp_fu_778_p0 = grp_fu_778_p00;

assign grp_fu_778_p00 = i_2_fu_431_p3;

assign grp_fu_778_p1 = 13'd86;

assign grp_fu_778_p2 = grp_fu_778_p20;

assign grp_fu_778_p20 = select_ln25_1_fu_485_p3;

assign grp_fu_786_p0 = grp_fu_786_p00;

assign grp_fu_786_p00 = reg_299;

assign grp_fu_786_p1 = conv3_i_i97_2_2_cast_reg_897;

assign grp_fu_793_p0 = grp_fu_793_p00;

assign grp_fu_793_p00 = image_in_q0;

assign grp_fu_793_p1 = conv3_i_i97_214_cast_reg_927;

assign grp_fu_800_p0 = grp_fu_800_p00;

assign grp_fu_800_p00 = reg_299;

assign grp_fu_800_p1 = conv3_i_i97_cast_reg_937;

assign grp_fu_808_p0 = grp_fu_808_p00;

assign grp_fu_808_p00 = reg_299;

assign grp_fu_808_p1 = conv3_i_i97_1_1_cast_reg_917;

assign grp_fu_815_p0 = grp_fu_815_p00;

assign grp_fu_815_p00 = image_in_q0;

assign grp_fu_815_p1 = conv3_i_i97_2_cast_reg_907;

assign grp_fu_821_p0 = grp_fu_821_p00;

assign grp_fu_821_p00 = image_in_q0;

assign grp_fu_821_p1 = conv3_i_i97_2_1_cast_reg_902;

assign i_2_fu_431_p3 = ((icmp_ln278_reg_288[0:0] == 1'b1) ? i_19_fu_126 : i5_fu_114);

assign i_fu_447_p2 = (i_2_fu_431_p3 + 7'd1);

assign icmp_ln25_fu_681_p2 = ((indvar_flatten2_fu_102 == 13'd7395) ? 1'b1 : 1'b0);

assign icmp_ln27_fu_670_p2 = ((image_1d_idx_7_reg_974 == select_ln25_2_fu_617_p3) ? 1'b1 : 1'b0);

assign icmp_ln45_fu_736_p2 = (($signed(tmp_1_reg_1124) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign image_1d_idx_1_fu_558_p2 = (select_ln25_reg_942 + 13'd88);

assign image_1d_idx_2_fu_544_p2 = (select_ln25_reg_942 + 13'd89);

assign image_1d_idx_3_fu_572_p2 = (select_ln25_reg_942 + 13'd90);

assign image_1d_idx_4_fu_598_p2 = (select_ln25_reg_942 + 13'd176);

assign image_1d_idx_5_fu_642_p2 = (select_ln25_reg_942 + 13'd177);

assign image_1d_idx_6_fu_409_p2 = (select_ln25_fu_393_p3 + 13'd178);

assign image_1d_idx_7_fu_463_p2 = (select_ln25_reg_942 + 13'd1);

assign image_1d_idx_fu_493_p2 = (select_ln25_reg_942 + 13'd2);

assign image_in_address0 = image_in_address0_local;

assign image_in_ce0 = image_in_ce0_local;

assign image_out_address0 = zext_ln52_1_fu_774_p1;

assign image_out_ce0 = image_out_ce0_local;

assign image_out_d0 = acc_sat_1_fu_765_p3;

assign image_out_we0 = image_out_we0_local;

assign j_fu_507_p2 = (select_ln25_1_fu_485_p3 + 7'd1);

assign mul_ln40_1_fu_531_p0 = mul_ln40_1_fu_531_p00;

assign mul_ln40_1_fu_531_p00 = image_in_load_1_reg_989;

assign mul_ln40_1_fu_531_p1 = conv3_i_i97_15_cast_reg_932;

assign mul_ln40_3_fu_589_p0 = mul_ln40_3_fu_589_p00;

assign mul_ln40_3_fu_589_p00 = reg_299;

assign mul_ln40_3_fu_589_p1 = conv3_i_i97_1_cast_reg_922;

assign mul_ln40_5_fu_629_p0 = mul_ln40_5_fu_629_p00;

assign mul_ln40_5_fu_629_p00 = reg_299;

assign mul_ln40_5_fu_629_p1 = conv3_i_i97_1_2_cast_reg_912;

assign select_ln25_1_fu_485_p3 = ((icmp_ln278_reg_288[0:0] == 1'b1) ? 7'd0 : j7_fu_122);

assign select_ln25_2_fu_617_p3 = ((icmp_ln278_reg_288[0:0] == 1'b1) ? add_ln25_111_fu_134 : indvars_iv353_fu_106);

assign select_ln25_3_fu_401_p3 = ((ap_phi_mux_icmp_ln278_phi_fu_291_p4[0:0] == 1'b1) ? ap_sig_allocacmp_add_ln2510_load : ap_sig_allocacmp_indvars_iv4_load);

assign select_ln25_fu_393_p3 = ((ap_phi_mux_icmp_ln278_phi_fu_291_p4[0:0] == 1'b1) ? ap_sig_allocacmp_add_ln2510_load : ap_sig_allocacmp_image_1d_idx6_load);

assign sext_ln40_3_fu_709_p1 = grp_fu_821_p3;

assign sext_ln40_4_fu_652_p1 = grp_fu_800_p3;

assign sext_ln40_6_fu_655_p1 = add_ln40_6_reg_1064;

assign sext_ln40_7_fu_717_p1 = $signed(add_ln40_7_reg_1084);

assign tmp_2_fu_741_p3 = acc_reg_1118[32'd20];

assign trunc_ln50_fu_748_p1 = acc_reg_1118[7:0];

assign zext_ln27_1_fu_443_p1 = select_ln25_reg_942;

assign zext_ln37_1_fu_498_p1 = image_1d_idx_fu_493_p2;

assign zext_ln37_2_fu_563_p1 = image_1d_idx_1_fu_558_p2;

assign zext_ln37_3_fu_549_p1 = image_1d_idx_2_fu_544_p2;

assign zext_ln37_4_fu_577_p1 = image_1d_idx_3_fu_572_p2;

assign zext_ln37_5_fu_603_p1 = image_1d_idx_4_fu_598_p2;

assign zext_ln37_6_fu_647_p1 = image_1d_idx_5_fu_642_p2;

assign zext_ln37_7_fu_415_p1 = image_1d_idx_6_fu_409_p2;

assign zext_ln37_fu_468_p1 = image_1d_idx_7_fu_463_p2;

assign zext_ln52_1_fu_774_p1 = add_ln52_reg_1019;

endmodule //axil_conv2D_axil_conv2D_Pipeline_loop_i_loop_j
